### PR TITLE
Trigger to get creation date.

### PR DESCRIPTION
**Pull request by susiecoleman**
We want to be able to group articles by day but still keep the exact time of creation. Using a trigger to create a column that stores this information so we don't need to do this in the scala api.

### CODE REVIEW

**Comment by mbarton** [comment]
Could we write this column when the article comes in rather than using a trigger? I agree with @akash1810 that it could be confusing

**Comment by susiecoleman** [comment]
@mbarton @akash1810 This is a bit of a work around as I can't do exactly what I want to do with slick which is to do a groupby by truncating the date so I only get the date not the time.
The options @marialivia16 and I came up with are:
1. This
2. Auto populate the field when inserting it into the database using the creation time
3. Do the groupby filtering in the code rather than when getting it out of the database

Any thoughts on what is the best solution?

**Comment by mbarton** [comment]
Not sure if this would work but [http://ben.goodacre.name/tech/Group_by_day,_week_or_month_%28PostgreSQL%29](this internet person) suggests that you can just use `date_trunc` at query time?

```
SELECT date_trunc('day', creation_time) AS "day" , count(*) AS "entries"
FROM metrics
WHERE creation_time > now() - interval '1 week' 
GROUP BY 1 
ORDER BY 1;
``` 

You can then pass that into Slick as a plain sql statement ```sql""" ... """.as[ResultType]```.

The 1 in `group by 1` `order by 1` refers to the first column. Definitely not sure this works but it would be clearer just to say `GROUP BY Day` if possible

**Comment by akash1810** [comment]
could you do a `GROUPBY date_part('date', creation_date)`?

**Comment by akash1810** [comment]
Alternatively store `creation_date` and `creation_time` as distinct columns; not sure what this'll do to db performance though.

**Comment by susiecoleman** [comment]
Fixed with alternative approach https://github.com/guardian/editorial-production-metrics/pull/33

**Pull request closed without merging**
