### PR TITLE
Add fluentbit

### PR DESCRIPTION
**Pull request by davidfurey**
## What does this change?

This PR aims to ship logs via [Fluent Bit](https://docs.fluentbit.io/manual/pipeline/outputs/kinesis) instead of using the standard [Logback Kinesis appender](https://github.com/guardian/kinesis-logback-appender). This was related to the general tools outage, more information can be found in the [incident document](https://docs.google.com/document/d/17jGwlvc5F-SOCSZ90lNl5ZRpJMvvaJ_UXtuUyY4ZM1s/edit#heading=h.98xvxa3bjhw).

~Entirely based on https://github.com/guardian/atom-workshop/pull/304~
~With a little bit from https://github.com/guardian/atom-workshop/pull/306/files to fix timestamps~

Uses the https://github.com/guardian/devx-logs, following the pattern from https://github.com/guardian/path-manager/pull/51 and https://github.com/guardian/editorial-tools-platform/pull/605

## How to test

Deploying to CODE in conjunction with the necessary CFN changes. Do the logs show up in ELK?

## How can we measure success?

Our logs no longer block the running application, they are therefore more reliable. More logs are also included as a result, which may be useful in debugging.

### CODE REVIEW

**Comment by davidfurey** [comment]
Tested in CODE as part of https://github.com/guardian/editorial-production-metrics/pull/229

**Comment by twrichards** [comment]
@davidfurey I paired with @akash1810 earlier to change my recent FluentBit impl. for `path-manager` (https://github.com/guardian/path-manager/pull/51 and https://github.com/guardian/editorial-tools-platform/pull/605) to use https://github.com/guardian/devx-logs solution instead. It's much simpler/cleaner and you get cloud-init logs for free.

**Comment by davidfurey** [comment]
@twrichards thanks, I've pushed some changes to take this new approach but haven't tested it yet. Since this is now state-of-the-art, we should upgrade our other projects to use this approach.

**Comment by davidfurey** [comment]
Logging works in CODE

**Review by twrichards — APPROVED** [review]
Code LGTM and I see you've tested in CODE - sorry for the delay

**Comment by twrichards** [comment]
Perhaps PR description could be updated to make it clear at a glance that it uses devx-logs

**Pull request merged**
